[theme]

# Primary accent for interactive elements
primaryColor = '#64CCC5'

# Background color for the main content area
backgroundColor = '#27005D'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#9400FF'

# Color used for almost all text
textColor = '#F5FCCD'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"